version: '3.8'

services:
  # Backend API service
  backend:
    image: arnozeng/scc-backend:latest
    volumes:
      - ./data:/app/data
      - ./backend:/app/backend
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - PYTHONPATH=/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend service
  frontend:
    image: arnozeng/scc-frontend:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # Mount certificate from aaPanel
      - /www/server/panel/vhost/cert/scc.arnozeng.com:/etc/nginx/ssl:ro
      # Mount nginx config for easy updates without rebuilding
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  data:
    driver: local

networks:
  default:
    name: scc-network
    driver: bridge 