version: '3.8'

services:
  # Backend API service
  backend:
    image: arnozeng/scc-backend:latest
    platform: linux/amd64
    ports:
      - "8000:8000"
    command: python -m uvicorn backend.src.api.app:app --host 0.0.0.0 --port 8000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend service
  frontend:
    image: arnozeng/scc-frontend:latest
    platform: linux/amd64
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s


networks:
  default:
    name: scc-network
    driver: bridge